"""add aprovacoes table

Revision ID: 6a1d267ec1fc
Revises: c290c40cc544
Create Date: 2026-06-03 00:12:34.945128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1d267ec1fc'
down_revision: Union[str, Sequence[str], None] = 'c290c40cc544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aprovacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('atendimento_id', sa.Uuid(), nullable=True),
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('detalhes', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos_pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes_pacientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Enable RLS on aprovacoes
    op.execute("ALTER TABLE aprovacoes ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE aprovacoes FORCE ROW LEVEL SECURITY;")
    op.execute("""
    CREATE POLICY tenant_isolation_policy ON aprovacoes
      USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop RLS policy
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON aprovacoes;")
    op.execute("ALTER TABLE aprovacoes NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE aprovacoes DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aprovacoes')
    # ### end Alembic commands ###
