"""initial_schema

Revision ID: 8263b8fa988a
Revises: 
Create Date: 2026-06-02 23:39:15.823308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8263b8fa988a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('whatsapp_numero', sa.String(length=50), nullable=False),
    sa.Column('plano', sa.String(length=50), nullable=False),
    sa.Column('sistema_ativo', sa.Boolean(), nullable=False),
    sa.Column('horario_abertura', sa.String(length=5), nullable=False),
    sa.Column('horario_fechamento', sa.String(length=5), nullable=False),
    sa.Column('limite_pedido_grande', sa.Integer(), nullable=False),
    sa.Column('cor_primaria', sa.String(length=7), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('revogado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.create_table('clientes_pacientes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('total_atendimentos', sa.Integer(), nullable=False),
    sa.Column('ticket_medio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ultima_consulta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_reativacao', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'whatsapp', name='uq_tenant_whatsapp')
    )
    op.create_table('configuracoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('horario_funcionamento', sa.String(length=2048), nullable=True),
    sa.Column('limite_pedido_grande', sa.Integer(), nullable=False),
    sa.Column('mensagem_boas_vindas', sa.String(length=1024), nullable=True),
    sa.Column('mensagem_fora_horario', sa.String(length=1024), nullable=True),
    sa.Column('mensagem_confirmacao', sa.String(length=1024), nullable=True),
    sa.Column('mensagem_reativacao', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('logs_mensagens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_whatsapp', sa.String(length=50), nullable=False),
    sa.Column('direcao', sa.String(length=10), nullable=False),
    sa.Column('mensagem', sa.String(length=4000), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos_produtos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('atendimentos_pedidos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('data_agendamento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_atendimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('compareceu', sa.Boolean(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('lojista_aprovado', sa.Boolean(), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes_pacientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lista_espera',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('servico_id', sa.Uuid(), nullable=True),
    sa.Column('data_preferida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes_pacientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos_produtos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('servico_id', sa.Uuid(), nullable=False),
    sa.Column('qtd_min', sa.Integer(), nullable=False),
    sa.Column('qtd_max', sa.Integer(), nullable=False),
    sa.Column('preco_particular', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_convenio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos_produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_atendimento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('atendimento_id', sa.Uuid(), nullable=False),
    sa.Column('servico_id', sa.Uuid(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('personalizacao', sa.String(length=1024), nullable=True),
    sa.Column('arquivo_arte_url', sa.String(length=1024), nullable=True),
    sa.Column('status_arte', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos_pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos_produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_atendimento')
    op.drop_table('precos')
    op.drop_table('lista_espera')
    op.drop_table('atendimentos_pedidos')
    op.drop_table('usuarios')
    op.drop_table('servicos_produtos')
    op.drop_table('logs_mensagens')
    op.drop_table('configuracoes')
    op.drop_table('clientes_pacientes')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_table('tenants')
    # ### end Alembic commands ###
