"""add_estados_conversa

Revision ID: c290c40cc544
Revises: 3706c1a6ad31
Create Date: 2026-06-03 00:02:28.061759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c290c40cc544'
down_revision: Union[str, Sequence[str], None] = '3706c1a6ad31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_conversa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('etapa_atual', sa.String(length=50), nullable=False),
    sa.Column('dados_acumulados', sa.String(length=2048), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes_pacientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id')
    )
    # ### end Alembic commands ###

    # Enable RLS on estados_conversa
    op.execute("ALTER TABLE estados_conversa ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE estados_conversa FORCE ROW LEVEL SECURITY;")
    op.execute("""
    CREATE POLICY tenant_isolation_policy ON estados_conversa
      USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop RLS policy
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON estados_conversa;")
    op.execute("ALTER TABLE estados_conversa NO FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE estados_conversa DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estados_conversa')
    # ### end Alembic commands ###
